name: Markdown lint

on:
  push:
    paths:
      - "**.md"
  pull_request:

jobs:
  skip-duplicate-actions:
    name: Skip duplicate actions
    runs-on: ubuntu-20.04
    outputs:
      should-skip: ${{ steps.skip-check.outputs.should_skip }}

    steps:
      - id: skip-check
        name: Check if workflow is not already running
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          concurrent_skipping: "same_content"
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  lint:
    name: Lint Markdown files
    needs: skip-duplicate-actions
    if: ${{ needs.skip-duplicate-actions.outputs.should-skip != 'true' }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown lint (markdownlint-cli)
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
